<?php

const RED_WINE_FIELDS = array(
    "varietal",
    "new_world",
    "garnet",
    "ruby",
    "purple",
    "red_fruit",
    "black_fruit",
    "blue_fruit",
    "nose_tart",
    "nose_ripe",
    "nose_overripe",
    "nose_baked",
    "palate_ripe",
    "palate_overripe",
    "palate_baked",
    "floral",
    "vegetal_pyrazine",
    "vegetal_tomato_leaf",
    "herbal_tobacco",
    "herbal_mint",
    "herbal_thyme_rosemary",
    "herbal_tea",
    "herbal_oregano_basil",
    "herbal_dried",
    "spice_pepper",
    "spice_anise",
    "spice_other",
    "coffee",
    "cocoa",
    "game",
    "smoke",
    "balsamic",
    "carbonic_maceration",
    "volatile_oxidation",
    "organic",
    "inorganic",
    "oak",
    "tannin_low",
    "tannin_mod",
    "tannin_mod_plus",
    "tannin_high",
    "acid_low",
    "acid_mod",
    "acid_mod_plus",
    "acid_high",
    "alcohol_low",
    "alcohol_mod",
    "alcohol_mod_plus",
    "alcohol_high",
    "climate_cool",
    "climate_moderate",
    "climate_warm",
    "description",
    "notes",
    "confusion",
);

const WINE_TEXT_FIELDS = array(
    "varietal",
    "description",
    "notes",
    "confusion",
);

const RED_WINE_NOTE_LABELS = array(
    "floral" => "Floral",
    "vegetal_pyrazine" => "Vegetal: Pyrazine",
    "vegetal_tomato_leaf" => "Vegetal: Tomato Leaf",
    "herbal_tobacco" => "Vegetal: Tobacco",
    "herbal_mint" => "Herbal: Mint, Eucalyptus",
    "herbal_thyme_rosemary" => "Herbal: Thyme, Rosemary",
    "herbal_tea" => "Herbal: Tea",
    "herbal_oregano_basil" => "Herbal: Oregano, Basil",
    "herbal_dried" => "Herbal: Dried",
    "spice_pepper" => "Spice: Black Pepper, Peppercorn",
    "spice_anise" => "Spice: Anise, Licorice",
    "spice_other" => "Spice: Other",
    "coffee" => "Coffee",
    "cocoa" => "Cocoa, Chocolate, Mocha",
    "game" => "Game, Blood, Cured Meat, Leather",
    "smoke" => "Smoke",
    "balsamic" => "Balsamic, Tar",
    "carbonic_maceration" => "Carbonic Maceration",
    "volatile_oxidation" => "Volatile Acidity, Oxidation",
    "organic" => "Organic Earth: Forest Floor, Wet Leaves, Mushrooms",
    "inorganic" => "Inorganic Earth: Stone, Rock, Mineral, Sulfur",
    "oak" => "New Oak: Vanilla, Smoke, Toast, Coconut",
);
